FROM doccano/doccano
VOLUME doccano-db:/data

ARG ADMIN_USERNAME
ARG ADMIN_EMAIL
ARG ADMIN_PASSWORD

EXPOSE 4000

# docker build . -t doccano/latest
# docker run -p 8000:8000 --name doc doccano/latest